language: go

script:
 - go build -v
 - go test -v

after_failure: failure
after_error: failure

notifications:
  email:
    recipients:
      - jragonmiris@gmail.com
    on_success: change
    on_failure: always
